#!/bin/sh

# param 
# --------------------------------------
# Main Variable:
MAIN_PATH="$(dirname $(cd $(dirname $0);pwd))"
SCRIPT_PATH="$MAIN_PATH/script" # !!!---------------->>>
SCRIPT_FILE_PATH="$SCRIPT_PATH/$(basename $0)"

# Upload common shell file:
source $SCRIPT_PATH/common
printOut $SCRIPT_PATH

declare -A properties
commands=()
commands[0]='--export'  # local plasmoids path
commands[1]='--import'  # local plasmoids path
commands[2]='--linklib' # libkdecorations2private lib source file

# User Settings:
SCRIPT_NAME=dtenv_script

# arr_check___Path=( \

# )
# -----------------------------------

# -----------------------------------
# Func:

# param1: source file
linkLib() {
    local LOCAL_SOURCE_FILE=$1
    ln -s $LOCAL_SOURCE_FILE /usr/lib/libkdecorations2private.so.9
}

# param1: local plasmoids path
importExtensions() {
    local LOCAL_PLASMAMOIDS_PATH=$1

    cp -Rf $LOCAL_PLASMAMOIDS_PATH/* $EXTENSIONS
}

# param1: local plasmoids path
exportExtensions() {
    local LOCAL_PLASMAMOIDS_PATH=$1

    checkMkdir $LOCAL_PLASMAMOIDS_PATH
    cp -Rf $EXTENSIONS/* $LOCAL_PLASMAMOIDS_PATH

    chown $ORIGINAL_USER:$ORIGINAL_GROUP -R $LOCAL_PLASMAMOIDS_PATH/*
    
    local USER_HOME_PATH="$(dirname $(dirname $(dirname $(dirname $LOCAL_PLASMAMOIDS_PATH))))"

    cd $USER_HOME_PATH
    out=$(./.local/share/plasma/plasmoids/org.kde.windowbuttons/lib-install.sh 2>&1)
    printOut "$out"
    printOut "Linked"
}

# Main
## Init Properties
while [[ $# -gt 0 ]];do
    # Key
    check_command commands $1
    if [[ $? == '0' ]];then
        key=$1
    else
        printERROR "Commands init ERROR"
        exit 1
    fi

    # Value
    check_command commands $2
    if [[ $? == '0' ]];then
        value=''
    else
        if [[ -z $2 ]];then
            value=''
        else
            value=$2
        fi
    fi

    setProperty properties $key $value
    if [[ -z $value ]];then shift 1; else shift 2; fi 
done

printProperties properties
sleep 4

## init check command
isExistKey properties '--export'
state1=$?
isExistKey properties '--import'
state2=$?
printOut "State1: $state1 | State2: $state2"
if [ $state1 == '1' ] && [ $state2 == '1' ];then
    printERROR "Missing key parameters"
    exit 1
fi
unset state1
unset state2

## Flow

isExistKey properties '--import'
if [[ $? == '0' ]];then
    importExtensions "${properties["--import"]}"
fi

isExistKey properties '--export'
if [[ $? == '0' ]];then
    exportExtensions "${properties["--export"]}"
fi

isExistKey properties '--linklib'
if [[ $? == '0' ]];then
    linkLib "${properties["--linklib"]}"
fi

printOut " ------- Execution complete ------- "